#!/usr/bin/python3

filename_brightness = '/sys/class/backlight/intel_backlight/brightness'
filename_max_brightness = '/sys/class/backlight/intel_backlight/max_brightness'

with open (filename_brightness) as file_brightness:
    brightness = int(next(file_brightness))
with open (filename_max_brightness) as file_max_brightness:
    max_brightness = int(next(file_max_brightness))
print('' + str(int(brightness / max_brightness * 100)) + '%')
